"""
Django settings for khabgah_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mk$sr%9jys)kqa!a#)plx_a7%(ydlb6_j%nfs%en3)hk00^&rc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://reservation-dorm.chbk.app/', 'https://www.reservation-dorm.chbk.app/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'khapp',
    'login',
    'reservation',
    'management',
]

AUTH_USER_MODEL='login.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'khabgah_project.urls'

import os

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'khabgah_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Config DB MySql for Server_Chabokan

# DATABASES = {
#     'default': {
#         'ENGINE': os.getenv("DB_ENGINE", "django.db.backends.mysql"),
#         'NAME': os.getenv("DB_DATABASE", "reservation372_ryan"),  # نام پایگاه داده
#         'USER': os.getenv("DB_USERNAME", "reservation372_ryan"),      # نام کاربری
#         'PASSWORD': os.getenv("DB_PASSWORD", "Ow19tIAWLtdr"),  # رمز عبور
#         'HOST': os.getenv("DB_HOST", "services.irn9.chabokan.net"),   # آدرس میزبان
#         'PORT': os.getenv("DB_PORT", 16584),        # پورت (پیش‌فرض MySQL)
#     }
# }

# Config DB MySql for Server_Localhost

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        'NAME': os.getenv("DB_DATABASE", "khabgahdb"),  # نام پایگاه داده
        'USER': os.getenv("DB_USERNAME", "root"),      # نام کاربری
        'HOST': os.getenv("DB_HOST", "localhost"),   # آدرس میزبان
    }
}

# Config DB SQLite

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# settings.py

TIME_ZONE = 'Asia/Tehran'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os

STATIC_DIR_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# URL برای دسترسی به فایل‌های استاتیک
STATIC_URL = '/static/'

# مسیرهایی که Django باید برای پیدا کردن فایل‌های استاتیک جستجو کند
STATICFILES_DIRS = [
    os.path.join(STATIC_DIR_PATH, 'static'),  # مسیر دایرکتوری static در ریشه پروژه
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import os

MEDIA_DIR_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(MEDIA_DIR_PATH, 'media')



